server:
  port : 8086

spring:
  datasource:
    driver-class-name: org.postgresql.postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Developer357
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
